[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  command = ""
  targetPort = 8888
  port = 8888
  autoLaunch = true
  framework = "none"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/#profile"
  to = "/profile.html"
  status = 301
  force = true

[[redirects]]
  from = "/#achievements"
  to = "/achievements.html"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
